apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "hdfs.fullname" . }}-nodemanager
  labels:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: nodemanager
    {{- include "hdfs.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hdfs.name" . }}
      app.kubernetes.io/component: nodemanager
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.nodemanager.pdbMinAvailable }}
