apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs.fullname" . }}-resourcemanager
  labels:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: resourcemanager
    {{- include "hdfs.labels" . | nindent 4 }}
spec:
  ports:
  - port: 8088
    name: web
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "hdfs.name" . }}
    app.kubernetes.io/component: resourcemanager
    app.kubernetes.io/instance: {{ .Release.Name }}
