{{- if .Values.ingress.nameNode.enabled -}}
{{- $fullname := include "hadoop.fullname" . -}}
{{- $ingressPath := .Values.ingress.nameNode.path -}}
{{- $httpPort := .Values.nameNode.httpPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-namenode
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: namenode
    {{- include "hadoop.labels" . | nindent 4 }}
{{- if .Values.ingress.nameNode.labels }}
{{ toYaml .Values.ingress.nameNode.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.nameNode.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.nameNode.ingressClassName }}
  ingressClassName: {{ .Values.ingress.nameNode.ingressClassName }}
{{- end }}
{{- if .Values.ingress.nameNode.tls }}
  tls:
  {{- range .Values.ingress.nameNode.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.nameNode.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $.Values.ingress.nameNode.pathType }}
            backend:
              service:
                name: {{ $fullname }}-namenode
                port:
                  number: {{ $httpPort }}
  {{- end }}
{{- end }}