# A headless service to create DNS records
{{- if .Values.singleSetup.enabled}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: master
    {{- include "hadoop.labels" . | nindent 4 }}
spec:
  ports:
  - name: dfs
    port: {{ .Values.nameNode.port }}
    protocol: TCP
  - name: webhdfs
    port: {{ .Values.nameNode.httpPort }}
  - name: webshdfs
    port: {{ .Values.nameNode.httpsPort }}
    targetPort: {{ .Values.nameNode.httpsPort }}
  - name: http
    port: 8088
    protocol: TCP
    targetPort: 8088
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end}}
