# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-datanode
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    {{- if .Values.singleSetup.enabled }}
    app.kubernetes.io/component: slave
    {{- else}}
    app.kubernetes.io/component: datanode
    {{- end}}
    {{- include "hadoop.labels" . | nindent 4 }}
spec:
  ports:
  - name: webhdfs
    port: {{ .Values.dataNode.httpPort }}
  - name: webshdfs
    port: {{ .Values.dataNode.httpsPort }}
  - name: web
    port: 8088
  - name: web2
    port: 8082
  - name: api
    port: 8042
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: slave
    app.kubernetes.io/component: namenode
    app.kubernetes.io/instance: {{ .Release.Name }}
